update

diff --git a/report b/report
--- a/report
+++ b/report
@@ -1,8 +1,8 @@
 #$!/bin/bash
-#$Id: report,v 1.443 2015/05/22 12:25:51 fulford Exp fulford $
+#$Id: report,v 1.444 2015/09/01 08:30:12 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/report,v $
-# $Revision: 1.443 $
-# $Date: 2015/05/22 12:25:51 $
+# $Revision: 1.444 $
+# $Date: 2015/09/01 08:30:12 $
 # Author C W Fulford.
 # Copyright 2012 - 2013 (c) C W Fulford. 
 # Licensed for public use under the LGPL.
@@ -18,7 +18,7 @@ while [ $# -gt 0 ];do
 		-o) odir=$2;shift 2;;
 		-s) display=:;shift;;
 		-v) verbose=:;shift;;
-		-V) echo "$cmd $Revision: 1.443 $"|awk '{print $1,$3}';exit;;  
+		-V) echo "$cmd $Revision: 1.444 $"|awk '{print $1,$3}';exit;;  
 		-*) echo "$syntax" >&2;exit 1;;
 		 *) id=$1;shift;;
 	esac
@@ -63,7 +63,8 @@ for mbox in $mboxes;do
 	if [ -f $mbox ];then
 		mcount=`grep -e "^Date: .*$month $year" $mbox|wc -l`
 	fi
-	admsgs=`expr "$admsgs" + "$mcount"`
+	admsgs=`expr "$admsgs" + "$mcount"` ||{ echo "$cmd: error line $LINENO -mcount = $mcount, admsgs = $admsgs, mbox =$mbox" >&2 ;}
+	
 done
 [ $debug ]&& echo "company = $company"
 
